### ISSUE TITLE
Add GUID type

### ISSUE THREAD

**Issue by vagifverdi** [fpco/odbc#10]
the sql column type is uniqueidentifier.

Here's the relevant code:

declarations:
```
sql_guid :: SQLSMALLINT
sql_guid = (-11)
```
getData:

`   | colType == sql_guid -> getGuid dbc stmt i   
`

the procedure:

```
getGuid :: Ptr EnvAndDbc -> SQLHSTMT s -> SQLUSMALLINT -> IO SqlValue
getGuid dbc stmt column = do
  let availableBytes = 36
      allocBytes = availableBytes + 1
  bufferp <- callocBytes (fromIntegral allocBytes)
  void
    (getTypedData
       dbc
       stmt
       sql_c_char
       column
       (coerce bufferp)
       (SQLLEN (fromIntegral allocBytes)))
  bs <- S.unsafePackMallocCStringLen (bufferp, fromIntegral availableBytes)
  let ts = decodeUtf8' bs
  case ts of
       Right x -> if T.head x == '\NUL' then pure SqlNull else evaluate (SqlText x)
       _ ->  evaluate (SqlByteString bs)

```
It is a bit hacky because I could not figure out how to get the size of the buffer so I'm just setting it to 36 and then checking if the first character is \NUL
I'm also converting it to Text, though you can chose to leave it as ByteString.

**Comment by chrisdone** [comment]
That sounds cool. I'll look into the length bit when I come round to it.

**Comment by MichelBoucey** [comment]
So when I try to retrieve a uniqueidentifier, which is in my case a primary key, I'm stuck on

`*** Exception: UnknownDataType "getData" (-11)`

**Comment by chrisdone** [comment]
Hey Michael. Can you give me a trivial `CREATE TABLE` schema with the exact field you're using, as a regression test?

**Comment by MichelBoucey** [comment]
CREATE TABLE uniqueId (col1 uniqueidentifier DEFAULT NEWSEQUENTIALID());

**Comment by paolino** [comment]
I'm also stuck on the (-11) missing colType. We cannot migrate from HDBC-odbc package until this is fixed. Is there a plan for this fix? how can I contribute to speed it up ?

**Comment by chrisdone** [comment]
I just need to sit down and implement this data type properly. I'll try to squeeze this in this week.
