### ISSUE TITLE
Using sql_c_char in getBytesData may lead to truncated or corrupted strings. Use sql_c_binary

### ISSUE THREAD

**Issue by vagifverdi** [fpco/odbc#11]
The problem is that sql varchar is encoded most of the time not in utf8 but in weird codepage win1251. Under that codepage most characters take 1 byte, but some take 2.

For example put into a varchar this string 'A®B®C-®end'
As you see there are 3 non ascii chars there. Then check what you are getting. Most likely the last 3 letters "end" will be missing. That's because sql_c_char reports number of visible characters rather than number of bytes they take to store. But if you replace it with sql_c_binary, then it all works fine.

**Comment by chrisdone** [comment]
Good point. I had originally thought `sql_c_char` _was_ an unaltered return of the characters. I had noticed that it does some funny encoding. I'll swap it out with `sql_c_binary` and check the test suite.

**Comment by chrisdone** [comment]
Test suite passes fine. Glad to have that cleared up. Thanks!
