### ISSUE TITLE
Allowing use with other Db drivers

### ISSUE THREAD

**Issue by mleone11** [fpco/odbc#13]
Hello, I know you wrote this library specifically for SQL Server but I'm attempting to use it for IBM iSeries. I'm able to successfully test it and get a connection, but I had to include the freeTDS library because of the odbcss.h dependency in cbits/odbc.c. Since I shouldn't need any of that, I'm wondering if it would be possible to add a cabal flag to disable the inclusion of that dependency?

**Comment by chrisdone** [comment]
I should have documented that -- I did need to install `freetds` too just for the header files. It's purely for data type definitions and is needed by `odbc.c`.

Are you saying you'd prefer not to have to install the freetds package for this header file?

What would the alternative be, that we include it in the cabal package directly? That's a possibility.

**Comment by chrisdone** [comment]
Meanwhile I'll document that freetds is needed for `odbcss.h` in the README.

**Comment by vagifverdi** [comment]
I simply copied the header file to the unixodbc include folder when I got error and it worked fine.
No need to install freetds.

**Comment by mleone11** [comment]
Nope, I can live with that if it's deliberate and necessary. And especially if it's documented 👍 
If you ever decide to maintain the header yourself, a heads up on here will be appreciated!

**Comment by chrisdone** [comment]
Cheers!
