### ISSUE TITLE
Troubleshoot "missing" lib

### ISSUE THREAD

**Issue by mleone11** [fpco/odbc#15]
So I include this tool as a dependency in my haskell app, and everthing builds. But when I invoke the code that calls ODBC.connect I get a runtime error from the unixODBC driver manager:

UnsuccessfulReturnCode "odbc_SQLDriverConnect" (-1) "[unixODBC][Driver Manager]Can't open lib '/opt/ibm/iaccess/lib64/libcwbodbc.so' : file not found[unixODBC][Driver Manager]Can't open lib '/opt/ibm/iaccess/lib64/libcwbodbc.so' : file not found"

I'm able to connect without issues using the standalone version of your tool (via stack, as your example shows). But something doesn't connect at runtime with my app. When I run ldd there are no missing links. And I've added the path to LD_LIBRARY_PATH in the shell. Have you ever experienced anything like this?

**Comment by chrisdone** [comment]
This library links against the ODBC library. Secondarily, there are N dynamic libraries for each driver which the ODBC library deals with. So this seems more like an ODBC misconfiguration issue.

What's your connection string? Are you trying to connect to an IBM database?

**Comment by chrisdone** [comment]
Did you get anywhere with it?

**Comment by mleone11** [comment]
Yes I am attempting to connect with an IBM Db, with the string "DSN=myDB_Dev"
myDB_Dev is defined in the odbc.ini file which uses the driver defined in odbcinst.ini. I know that the ODBC in combo with the IBM driver works because I can connect with the isql command as well as with your tool (stack exec odbc "DSN=myDB_Dev")

I know it's not an issue with your library, but I was just taking a shot that you might know something helpful. Feel free to close this at any time!

**Comment by mleone11** [comment]
BTW this is my haskell:
myFunc :: MonadApp m
  => m ()
myFunc = do
  conn <- ODBC.connect "DSN=myDB_Dev"
  rows <- ODBC.query conn "SELECT * FROM TABLE_1 LIMIT 3"
  mapM_ (liftIO . display) rows
  _ <- ODBC.close conn
  return ()
  where
    display=...

**Comment by chrisdone** [comment]
OK. Going to close. But if you find the reason why please update me and I'll add it to the docs if it's useful to others!
