### ISSUE TITLE
Uncaught exception running odbc test app

### ISSUE THREAD

**Issue by rrottier** [fpco/odbc#17]
I am running OSX 10.13.4 (17E202) with the latest microsoft odbc.  Using both lts 9.21 and 10.10, when I run:
stack exec odbc 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=172.16.191.157;Uid=username;Pwd=password'

I get the following error:
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for C/en_AU.UTF-8/C/C/C/C

**Comment by rrottier** [comment]
Does not happen with driver 13.1

**Comment by chrisdone** [comment]
Looks like this was explored thoroughly in https://github.com/Microsoft/homebrew-mssql-release/issues/18

Culprit is the driver itself, not this Haskell binding to it. Thanks for reporting. 

I'll add a note in the README about it so that OS X users can avoid this issue with driver v17.
