### ISSUE TITLE
Add quasi quoter for string interpolation

### ISSUE THREAD

**Issue by YoEight** [fpco/odbc#19]
Greetings.
Firstly, I wanted to thank all people involved in this library personally. I was using an older and probably not longer maintain odbc-like library. I'm far more assured to know FPComplete is going to support this one.

I'm using `odbc` at my job, and I was wondering if you might be interested in a small patch of mine. Basically, what that patch does, it's to support SQL interpolation. How parameter insertion is done in `odbc` is not suitable for big SQL queries or if you want to store your SQL queries out of your Haskell source code. I added snippets (by introducing `sql` quasi-quote and `sqlFile` template haskell splice) on how we use the SQL interpolation at my work. 

If you like the idea, I'll be more than happy to submit a PR by the end of the week.

```haskell
{-# LANGUAGE QuasiQuotes #-}

import Database.ODBC.SQLServer(Query, ToSql(..))

select_some_stuff :: Text -> Int -> Query
select_some_stuff name age = [sql|select * from user where age = $age AND name = $name|]
```

```haskell
{-# LANGUAGE TemplateHaskell #-}

import Database.ODBC.SQLServer(Query, ToSql(..))

select_some_stuff :: Text -> Int -> Query
select_some_stuff name age = $(sqlFile "path/to/my/ugly/sql/file.sql")
```
```
$ cat path/to/my/ugly/sql/file.sql
select * from user where age = $age AND name = $name
```

**Comment by chrisdone** [comment]
That looks good to me. I'd merge a PR with that. :+1: :smile:
