### ISSUE TITLE
Conversion failed when converting character string to smalldatetime data type.

### ISSUE THREAD

**Issue by YoEight** [fpco/odbc#21]
Greetings,

I stumble upon that error, and I know why and hopefully how to fix it. I got that error when querying an MS SQLServer 2012 edition server.

It boils down to how `LocalTime` are serialised. `odbc` serializes `LocalTime` like this
`'2018-07-03 10:05:09.77076'` which causes that error message on my machine™

```
UnsuccessfulReturnCode "odbc_SQLExecDirectW" (-1) "[Microsoft][ODBC Driver 13 for SQ
L Server][SQL Server]Conversion failed when converting character string to smalldatetime data type.[Microsoft][OD
BC Driver 13 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data
type."
```

If we strip everything after the second value, it works as expected (ex: `'2018-07-03 10:05:09'`)

Thanks for your time.

**Comment by chrisdone** [comment]
If we strip that for all `LocalTime` values, then people would lose precision on a regular datetime field.

Perhaps it's worth re-thinking how we write time types to the database. Currently, I've documented that writing a `LocalTime` or a `TimeOfDay` loses precision on the decimal places of seconds. 

![screenshot from 2018-07-03 09-51-57](https://user-images.githubusercontent.com/11019/42209597-f884794a-7ea6-11e8-9fdf-f22b046bd37c.png)

Rounding that up to whole seconds would be a big loss.

**Proposal**: Have a `Datetime2` newtype and a `Smalldatetime` newtype wrapping around `LocalTime`  like this:

```haskell
newtype Datetime2 = Datetime2 { unDatetime2 :: LocalTime }
  deriving (Eq, Ord, Show, Read, FormatTime) 
newtype Smalldatetime = Smalldatetime { unSmalldatetime :: LocalTime }
  deriving (Eq, Ord, Show, Read, FormatTime) 
```

which have different instances of `ToSql`, and we remove (or add a custom type error to) the instance of `ToSql` for `LocalTime`, so that users have to pick the correct instance.

**Comment by YoEight** [comment]
Looks sensible.

In the meantime, I will use a fork of `odbc` with my hack until your changes make it to master.

**Comment by chrisdone** [comment]
Pushed to hackage as odbc-0.1.0. Major version bump because this removes an instance.

Wrap your value in this type: http://hackage.haskell.org/package/odbc-0.1.0/docs/Database-ODBC-SQLServer.html#t:Smalldatetime

**Comment by chrisdone** [comment]
Wait a sec, I didn't update the test suite properly. This isn't correct yet. I'll update it.

The following query still fails: `INSERT INTO test VALUES ('1779-05-02 06:03:52.0')`

**Comment by chrisdone** [comment]
Oh, actually, it's fine. `.0` is okay. It's actually the _year_ that's out of bounds.
```sql
v

**Comment by chrisdone** [comment]
Just FYI, the `.xxx` syntax is allowed but ignored:

```sql
create table test (x smalldatetime);
Rows: 0
> INSERT INTO test VALUES ('1900-08-20 08:41:14.123456789');
UnsuccessfulReturnCode "odbc_SQLExecDirectW" (-1) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type."
> INSERT INTO test VALUES ('1900-08-20 08:41:14.12345678');
UnsuccessfulReturnCode "odbc_SQLExecDirectW" (-1) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type."
> INSERT INTO test VALUES ('1900-08-20 08:41:14.1234567');
UnsuccessfulReturnCode "odbc_SQLExecDirectW" (-1) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type."
> INSERT INTO test VALUES ('1900-08-20 08:41:14.123456');
UnsuccessfulReturnCode "odbc_SQLExecDirectW" (-1) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type."
> INSERT INTO test VALUES ('1900-08-20 08:41:14.12345');
UnsuccessfulReturnCode "odbc_SQLExecDirectW" (-1) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type."
> INSERT INTO test VALUES ('1900-08-20 08:41:14.1234');
UnsuccessfulReturnCode "odbc_SQLExecDirectW" (-1) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type.[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting character string to smalldatetime data type."
> INSERT INTO test VALUES ('1900-08-20 08:41:14.123');
Rows: 0
> select * from test;
1900-08-20 08:41:00
Rows: 1
> 
```

Which is good.

**Comment by chrisdone** [comment]
> If we strip everything after the second value, it works as expected (ex: '2018-07-03 10:05:09')

Oh, I just realized that smalldatetime doesn't include seconds. So when you insert `'2018-07-03 10:05:09'` you'll get back `'2018-07-03 10:05:00'`.

Needs more rounding in the output.

**Comment by YoEight** [comment]
Thanks @chrisdone  it works on my machine™ now. I went with `Smalldatetime` as `Datetime2` doesn't work with my MS SQLServer version (ending with the same error message I got in the first place, **as expected**).

Thanks again for the fantastic reactivity!
