### ISSUE TITLE
Null uniqueidentifier returns non-null value

### ISSUE THREAD

**Issue by spencerjanssen** [fpco/odbc#30]
I noticed that the query `select cast(null as uniqueidentifier)` results in a 16 byte `BinaryValue` instead of `NullValue`.

**Comment by chrisdone** [comment]
Good catch. I haven't heard of that, looking it up [I see](https://docs.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql?view=sql-server-ver15):

> Is a 16-byte GUID.

So the size matches up with the `uniqueidentifier` type, even if we ought to expect a `NULL` here. 

Looking at [the code responsible](https://github.com/fpco/odbc/blob/9830d4c2cc7cc93b1c537b8ebe64e2460ba3f856/src/Database/ODBC/Internal.hs#L677-L691), I see that I wrote the code (but don't remember doing so). A fix may be to use `getSize` as used [elsewhere](https://github.com/fpco/odbc/blob/9830d4c2cc7cc93b1c537b8ebe64e2460ba3f856/src/Database/ODBC/Internal.hs#L744-L747) to detect `NULL` and return `NullValue`.

**Comment by chrisdone** [comment]
I'll fix this, as I already happen to have the project open today.
