### ISSUE TITLE
Render a varchar value without encoding

### ISSUE THREAD

**Issue by rakeshkky** [fpco/odbc#49]
I have the following use case; I want to insert a `Text` value into a column of `varchar` type.
```haskell
import Data.Text.Encoding (encodeUtf8)

renderVarcharText :: Text -> Text
renderVarcharText = renderValue . ByteStringValue . encodeUtf8
```

The `renderVarcharText` function for `£` char generates `(''+CHAR(194)+''+CHAR(163)+'')` SQL snippet, on evaluating
```sql
SELECT (''+CHAR(194)+''+CHAR(163)+'')
```
returns `Â£`. That said, `Â£` is UTF8 encoded value of `£`. 

I want to render the value without encoding. I can use `TextValue` constructor, but it generates the literal with `N` prefixed, which is a value of `nvarchar` type. 

However, I could be able to insert `£` value into `varchar` column 
```sql
create table test_table (varchar_column varchar(8));
insert into test_table (varchar_column) values ('£') ;
```

I'm not sure, but, maybe I'm missing something. Please help me to render a `Text` value as `varchar` type without encoding.

**Comment by rakeshkky** [comment]
Using [`pack`](https://hackage.haskell.org/package/bytestring-0.11.3.0/docs/Data-ByteString-Char8.html#v:pack) from [`Data.ByteString.Char8`](https://hackage.haskell.org/package/bytestring-0.11.3.0/docs/Data-ByteString-Char8.html) instead of `encodeUtf8` renders the value as expected.
```haskell
import Data.ByteString.Char8 qualified as BS8
import Data.Text qualified as T

renderVarcharText :: Text -> Text
renderVarcharText = renderValue . ByteStringValue . BS8.pack . T.unpack
```

I'm not sure about the correctness of the function mentioned above.

**Comment by psibi** [comment]
Summarizing what we discussed:

- The generation of `''+CHAR(194)+''+CHAR(163)+'')` in the SQL snippet is the correct behavior and it is intended for proper escaping.
- Having a prefix of `N` when using TextValue does the proper insertion.

That being said, the recommendation is to use `TextValue` if you are using `nvarchar` and `ByteStringValue` if you are using `varchar`.

@rakeshkky  Is there anything else you want me to investigate in this issue ?

**Comment by rakeshkky** [comment]
@psibi You recommended to capture values from the user as `ByteString` instead `Text` and use `ByteStringValue` to construct the `Value`. In our case, it is hard to capture the values as `ByteString` and so we use `TextValue` which generates the SQL with `N` prefix. The database does cast (implicitly) to `varchar` while inserting.

**Comment by psibi** [comment]
Yeah, I saw that PR and from a quick look it LGTM.

I'm closing this issue as I don't see anything that needs to be done. But free feel to re-open if things aren't clarified. Thanks!
