### ISSUE TITLE
Add NULL value to Value type, drop the Maybe requirement

### ISSUE THREAD

**Issue by vagifverdi** [fpco/odbc#8]
1.The specifics of web development, basically ensure that I have to deal with both sql server and marshalling data from it to json in every module. Having both Aeson and Sql Server use the same name Value for the type is not convenient.

2. The database is inherently nullable and SqlValue is already a sum type. It makes sense to bake in SqlNull and get rid of the pervasive extra layer of Maybe. Also json takes the same approach.
Since SqlValue is a low level marshalling type meant to fetch data from external source (like json), I think handling nulls should be done the same way too.

**Comment by chrisdone** [comment]
I'll add a `Null` constructor to `Value`.

**Comment by chrisdone** [comment]
I have `Value` more than once in a bunch of projects already, I just qualify Aeson and SQL. It's not worth copying HDBC in this way. I'll just end up writing `SQL.SqlValue`. You can just define `type SqlValue = SQL.Value`.

**Comment by vagifverdi** [comment]
I agree. Naming is more of a opinion rather than necessity.
